### PR TITLE
group compile*.bat and upper/lowercase

### PR DESCRIPTION
**Pull request by JoseQuintas**

### CODE REVIEW

**Comment by JoseQuintas** [comment]
Reduce lines by using if /i, and group compile*.bat, renaming internal names
Do not change the way it works, and continue needing compile30.bat, compile32.bat and compilexb.bat
They will be used on another BATs too, for same test.
No matter about content.

**Comment by JoseQuintas** [comment]
group buildapp.bat + buildapp30.bat + buildapp32.bat
buildapp30.bat and buildapp32.bat can be deleted, because test now is over compileXX.bat.

**Comment by JoseQuintas** [comment]
ok the same on other files.
Please review and before delete files, need to change distro.

A bad comment:
At momment, I create my own HBP files, because OOHG HBP can't be used without BAT.
Harbour DO NOT NEED BATs, the only thing to solve is to use resource file + resource OOHG.
Not sure if is available to use in this way on OOHG, Harbour 3.x and XHarbour  

```
FUNCTION JPEGBancoItau()

   #pragma __binarystreaminclude "image\banco341.jpg" | RETURN %s
```
If available, user resource + oohg resource do not need extra process.

**Comment by fyurisich** [comment]
I'm going to incorporate the updates to compile_bcc.bat, compile_pc.bat and compile_vc.bat.
But not the other ones because compile30.bat, compile32.bat, compileXB.bat, buildapp30.bat and buildapp32.bat became non functional. The user looses the possibility to use them for compiling without any gain in return.
Also, what if the user decides to remove compile*.bat because he prefers to use buildapp.bat?
He can´t compile anymore because now one method of compiling depends on the other.
This is a no go for me. Both method should remain separated to give maximum flexibility.

**Comment by JoseQuintas** [comment]
Maximum flexibility? Are you sure?
What I need to do, to you remove all BATs about Harbour?
What kind of test you need?

**Comment by fyurisich** [comment]
The sole purpose of OOHG.HBP is to build the library.
Since MinGW can only add one resource file per project we can't embed oohg's rc into the compiled libraries.
Since to build and app you must create your own .hbp you can create an rc file for your project using an include.
Then you can add this new rc file to your .hbp as another input file and use hbmk2 without .bat
Try this:
////////// hbp file
#
# test.hbp
#
-n1
-ic:\oohg\include
-Lc:\oohg\lib\hb\mingw
-fullstatic
-gui
-loohg
-lhbprinter
-lminiprint
-lbostaurus
-lxhb
-lhbct
-lhbwin
test.prg
test.rc

////// test.rc
#include "C:\OOHG\RESOURCES\OOHG.RC"
I1 PNG one.png
I2 PNG two.png

To make:
PATH=C:\OOHG\HB32\BIN;C:\OOHG\HB32\MINGW\BIN
HBMK2 test.hbp

**Comment by fyurisich** [comment]
I do not want to force the user to change to a new building method.
You are welcome to add new methods of building apps but not to eliminate existing ones.

**Comment by JoseQuintas** [comment]
if you like the new bat, this could be an option.
Same options are available, 4 bats are available, but only one bat to maintain.

**Comment by JoseQuintas** [comment]
same on another bats, and correction

**Comment by fyurisich** [comment]
That's OK.

**Pull request merged**
