### PR TITLE
Using on Harbour 3.4, error when compile sample about duplicate declarations

### PR DESCRIPTION
**Pull request by JoseQuintas**
…ration

### CODE REVIEW

**Comment by JoseQuintas** [comment]
Please check about this:
/*
This constant must be defined when building libraries that
include oohg.ch to avoid forcing the request on every app.
define GTGUI_REMOVE if you want to use CONSOLE, GTWVW or GTWVG as default
*/
#ifndef GTGUI_REMOVE
REQUEST HB_GT_GUI_DEFAULT
#endif

**Comment by JoseQuintas** [comment]
need to make more tests

**Comment by fyurisich** [comment]
Thanks, Jose for you contribution.
I've just added GTGUI_REMOVE.
The errors caused by duplicate declarations were already fixed.
I will test the changes in .hbc files because I'm not familiar with the options you used
Regards.

**Comment by JoseQuintas** [comment]
NO !
I cancel the pull request to make more tests.
I discover a better option to use on USER SIDE

ANNOUNCE HB_GTSYS
REQUEST HB_GT_WVG_DEFAULT

No matter if lib uses GTGUI, this overwrites LIB changes.
But, I do not know if same works using GTWVW
There are 3 Windows GT on Harbour: GTWVG, GTWVW, and the native GTWVT
GTWVT is part of Harbour core, with equivalent for Linux 
GTWVW was the first of them, but on Harbour 3.2 it is on extras folder, do not considered as official contribution. On Harbour 3.4 Viktor updates it including 64 bits
GTWVG from XHarbour do not have Windows API 
GTWVG is GTWVT + Windows API Controls
May be you will like to see these source code:
https://github.com/vszakats/hb/blob/master/contrib/gtwvg/wnd.prg
https://github.com/vszakats/hb/blob/master/contrib/gtwvg/pushbut.prg
or my test (some in use)
https://github.com/JoseQuintas/libjpa/blob/master/source/ze_wvgtst.prg

**Comment by JoseQuintas** [comment]
About options of hbmk2:
${hb_plat} is platform win/linux and others
${hb_comp} is compiler: mingw, mingw64, bcc, bcc64, pocc, pocc64, msvc, msvc64 and others

Advantage about to use one folder for each compiler, is that you can have all on same machine
lib/win/mingw   lib/win/mingw64   lib/win/bcc lib/win/msvc

if you use hbmk2, you do not need any batch file.
if use all features, you could run oohg source code without compile/link, including multilanguage usage, and make doc like Harbour does.
This is made using hbmk2 and doc folders on Harbour
https://harbour.github.io/doc/harbour.html#hb_eol
At momment, only english and a limited portuguese option available.
And if you use same features as github Harbour 3.4, you never more need to create packages, they are made automatically on github when commit files.
It seems that few people noticed the changes

**Pull request closed without merging**
