### PR TITLE
Do not require hb_IsNil() from bad xhb.lib

### PR DESCRIPTION
**Pull request by JoseQuintas**
xhb compatibility library is a bad option to use.
Removed the needed of hb_isNil()

### CODE REVIEW

**Comment by fyurisich** [comment]
hb_IsNil is part of Harbour's RTL so xhb define is not used.
The only functions from xhb used by OOHG are TTOC, CTOT, PrintFileRaw and GetDefaultPrinter.
To avoid using this functions under Harbour, I'm going to add some translate to i_hb_compat.ch file

**Comment by JoseQuintas** [comment]
Harbour 3.2
```
d:\github\harbour32>hbmk2 -find isnil
xhb.hbc (installed):
   hb_IsNIL()
addons\hmg3\hmg3_core.hbc (not installed):
   bt_fillrectisnil()
addons\hmge\hmge_bostaurus.hbc (not installed):
   bt_fillrectisnil()
addons\oohg\oohg_bostaurus.hbc (not installed):
   bt_fillrectisnil()
```
Harbour 3.4
```
d:\harbour\contrib\xhb>hbmk2 -find isnil
xhb.hbc (installed):
   hb_IsNIL()
addons\hmg3\hmg3_core.hbc (not installed):
   bt_fillrectisnil()
addons\hmge\hmge_bostaurus.hbc (not installed):
   bt_fillrectisnil()
addons\oohg\oohg_bostaurus.hbc (not installed):
   bt_fillrectisnil()
```

**Comment by JoseQuintas** [comment]
on contrib\xhb\hbfunc.c

```
#if ! defined( HB_LEGACY_LEVEL5 )

HB_FUNC( HB_ISNIL )
{
   hb_retl( HB_ISNIL( 1 ) );
}

#endif
```

**Comment by JoseQuintas** [comment]
ok, on Harbour 3.2 is on valtype.c, but same #if ! defined( HB_LEGACY_LEVEL5 )
Means that may be available, if not activate LEGACY_LEVEL5.

**Comment by JoseQuintas** [comment]
There is a difference about using LEGACY_LEVEL5.
if on: hb_isnil() is part of xhb
if off, hb_isnil() is part of core

**Pull request merged**
