### PR TITLE
new compile.bat, delete compilexb.bat, compile30.bat, compile32.bat

### PR DESCRIPTION
**Pull request by JoseQuintas**
Notes about changes:

- shift /1 is the same as shift, but REMOVE parameter from list
- :CLEAR_ALL clear the parameters, then when test if empty will create with default (as before)
- call :ANY is like call a external bat, but calls a internal routine
- %* is ALL list without limit, not only %1 %2 %3 %4 %5 %6 %7 %8 %9
- On previous bat, "if exist compile30.bat" may have a extra use of test current folder, then use "if exist compile.bat" as a workaround.

Notes:

On compilexb.bat, one part sets HG_BCC and other HG_MINGW as BCC path. then set the 2 on new bat

On compile_bcc.bat, compile_mingw.bat, compile_pc.bat, compile_vc.bat
They create a file init.cld with text "OPTIONS NORUNATSTARTUP".
Do not found where it is used.

If update, need remove files from distros creation

### CODE REVIEW

**Comment by JoseQuintas** [comment]
This is the first time I use ELSE on bat, 
it was needed because of remove first element (shift /1)

**Comment by JoseQuintas** [comment]
Same with buildlib.bat, step by step
other 2 bat files deleted.

**Comment by JoseQuintas** [comment]
And now, preparing another files.
NOT now, but after changes, will be possible to delete 5 files: buildapp30.bat, buildapp32.bat, makelib30.bat, makelib32.bat, makelibxp.bat.
Same as previous changes.

**Comment by JoseQuintas** [comment]
deleted + 3 bat files

**Comment by JoseQuintas** [comment]
My fault.
shift or shift/1 do not affects %*, then change back to %1 %2 %3 %4 %5 %6 %7 %8 %9

delete buildapp30.bat, buildapp32.bat, buildapp_hbmk2.bat
buidapp.bat have all of them.

**Comment by fyurisich** [comment]
Which is the Window's minimum required version to run this new bats?

**Comment by fyurisich** [comment]
From what I see, in this new bats the autodetection of Harbour's version is lost.
You must do "BuildApp HBXX file" even if only one version is installed.
That's a big change from the current situation "BuildApp file".
And that change impacts directly on the user.
Before any further development please tell me the benefits these changes offer the user.

**Comment by JoseQuintas** [comment]
test now on Windows XP and works ok.

if bats are used to detection, then need to use a new file.
example: if exists %HG_HRB%\hbmake.exe then is xharbour, if exists hbmk2.exe then is Harbour.
if exists gcc.exe then is mingw, if exists bcc32.exe then is Borland C

**Comment by JoseQuintas** [comment]
may be anything like this

**Comment by fyurisich** [comment]
XP as minimum is ok.
Loosing functionality just to have less .bats it's not ok. 
Autodetection may work if there's a reliable way of differentiating HB 3.0 from 3.2 from 3.4

**Comment by JoseQuintas** [comment]
At momment I will save current changes out of fork, and reset fork.

**Pull request closed without merging**
