### PR TITLE
hbp + format

### PR DESCRIPTION
**Pull request by JoseQuintas**
your last change was h_application.prg, then use it as reference.

hbp:
change to test samples:  on source folder:  hbmk2 *.hbp
remove -ko because is Harbour default, and does not exists on xHarbour

hbx:
enable creation
it is interesting to check hbx. I found function abm2borrar, abmlistado, abmlistadoevento, abmlistadoimprimir. not sure if will be translated.
report a issue https://github.com/vszakats/harbour-core/issues/325

format:
working using alphabetical order: bostaurus.prg, h_activex.prg, h_anigif.prg

### CODE REVIEW

**Comment by JoseQuintas** [comment]
please confirm miniprint.prg about codepage.
View source code on my text editor and on GitHub and seems ok.
My text editor uses ANSI or UTF-8, same found on file, but no codepage option.
Not sure if it uses Windows default or file default, but on gihub shows same characters as before, without any change.

**Comment by fyurisich** [comment]
Source code file must be ANSI.

**Comment by JoseQuintas** [comment]
this h_edit_ex was the source code that was needing more formatting until now. I can't imagine anybody working with this source as it was.

**Comment by fyurisich** [comment]
I've merged most of the files.
I'll check the others asap.
Thanks for you contribution.

**Pull request merged**
