### PR TITLE
Few changes on bat/hbp

### PR DESCRIPTION
**Pull request by JoseQuintas**
bats: only first step: format
hbps: relative path
will make step by step, to understand each bat, and to make easy confirm changes.

Doubts:

Why xml.bat ?
Why bat for Harbour if hbmk2 is part of it?
Why 2 manifest 32/64 bits, if can be a single one?

At momment, to a rework on bats/hbp, only 2 steps to think::
manifest can be a single file
resource, can be the same until a better solution, because of oohg + app resource

### CODE REVIEW

**Comment by JoseQuintas** [comment]
on bat %* represent all parameters. bether than %1 %2 %3 %4 %5 %6 %7 %8 %9 because have no limit.
but this could not be changed where begans on %2, without use of %1, then limit continues on some parts and syntax too.

**Comment by fyurisich** [comment]
Hi, José:

Thank you for your contributions.
Please be so kind to submit the necessary changes to core/ChangeLog.txt
I'll commit to master asap.

Regarding your questions:

- Why xml.bat ?
I don't remember. I'll look into it.

-Why bat for Harbour if hbmk2 is part of it?
Running hbmk2 directly requieres that you add Harbour's folder to Window's PATH.
Since OOHG it's not a Harbour's product but a standalone development environment, the only required change is to add OOHG's folder to PATH.

-Why 2 manifest 32/64 bits, if can be a single one?
Maybe. The only difference is "processorArchitecture" entry. Since MS states this entry is optional, it's possible. Please be so kind to remove it and run some tests.

Regards
Fernando

**Comment by JoseQuintas** [comment]
Now, it is only decide if name will be makelib.bat or builblib.bat.

**Comment by JoseQuintas** [comment]
```
Since OOHG it's not a Harbour's product but a standalone development environment, 
```
I think about this.
The binaries download of OOHG can be considered as the official environment?
Harbour 3.2 + mingw
This solve any question about all organization.
Will work by default in same environment, with option to use any environment, any Harbour/xHarbour and any C compiler.
Once hbmk2 is part of OOHG environment, xHarbour user will have it when download oohg, do not need external link to get it.

**Comment by fyurisich** [comment]
The user can choose to use the libraries built with BCC + xHarbour.
In that distro hbmk2 is not present.

**Comment by JoseQuintas** [comment]
close pull because now it have conflicts. seems all changes are cumulative until merge.
May be better, I will group all changes in one or two commits before new pull request.

**Pull request closed without merging**
