### PR TITLE
format bats on PRG style

### PR DESCRIPTION
**Pull request by JoseQuintas**
This is the format only. Please unify all.
Will do the same on all bats of all repositories.
After change all bats, will wait commit before new changes.

### CODE REVIEW

**Comment by JoseQuintas** [comment]
Only format. 
If possible, define what are the "official" bats, or what bats are used.
Or MAIN bats, where others can be moved inside these.
We can change all to 2 BATS: one to build lib and one to build EXE, if not a unique bat.

**Comment by JoseQuintas** [comment]
if %HG_ROOT% will allways exists, and points to CORE folder, can began to move bat routines to %HG_ROOT%\oohgaux.bat
Please check about valid bats, if MAKE or BUILD, because there are small differences between them.
At momment no change, except format bats.

**Comment by fyurisich** [comment]
Unifying all bats into only two is a good option if and only if the resulting bat is easier to maintain and use.
Please give it a try.

**Comment by fyurisich** [comment]
Thank you.

**Comment by JoseQuintas** [comment]
Yes will be easy to maintain. 

First step is to be sure that oohgaux.bat exists on distro.
Can't change bats to a file that does not exists.

Make the change here: (and format bats)
https://github.com/oohg/distros/pull/1

No change. only add the file, to be sure it exists.

**Pull request merged**
