### PR TITLE
only format columns, line spacing and extra blank spaces

### PR DESCRIPTION
**Pull request by JoseQuintas**
my text editor remove trailing spaces on lines, then show as changes.
In first step only format columns and blank lines.
it is partial, to confirm if can be done on this way, before change all.
Because may be difficult to view what was changed, better do not change nothing than this on this step.

### CODE REVIEW

**Comment by JoseQuintas** [comment]
see now, on URL, we can add ?w=1 and changes about whitespace are hidden on view. it is a easy way to see a more clean compare.

**Comment by fyurisich** [comment]
How did you do this?
By hand?
Or using hbformat?
Or ...?

**Comment by JoseQuintas** [comment]
by hand.
Sometimes I like do it by hand, because can review another parts of source code.
And hbformat is dangerous to use when source code have C code, or over xHarbour code or over HMG code.

**Comment by fyurisich** [comment]
You're right, that's why I forked hbformat.
Someday will have our own formatter.

**Comment by fyurisich** [comment]
Merge done.
Thank you for your work.

**Pull request merged**
